server:
  port: 8080

  error:
    include-message: always
    include-binding-errors: always

spring:
  output:
    ansi:
      enabled: always

  application:
    name: customer

  datasource:
    driver-class-name: org.postgresql.Driver
    username: amigoscode
    password: password
    url: jdbc:postgresql://postgres:5432/customer

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  zipkin:
    baseUrl: http://zipkin:9411
    sender:
      type: rabbit
  
  rabbitmq:
    addresses: rabbitmq:5672
    username: guest
    password: guest

management:
  tracing:
    sampling:
      probability: '1.0'

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true