server:
  port: 8761

spring:
  output:
    ansi:
      enabled: always

  application:
    name: eureka-server

  zipkin:
    baseUrl: http://localhost:9411
    
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/