server:
  port: 8083

  error:
    include-message: always
    include-binding-errors: always

spring:
  output:
    ansi:
      enabled: always

  application:
    name: api-gateway

  zipkin:
    baseUrl: http://zipkin:9411
    
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**

management:
  tracing:
    sampling:
      probability: '1.0'
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true