server:
  port: 8761

spring:
  output:
    ansi:
      enabled: always

  application:
    name: eureka-server

  zipkin:
    baseUrl: http://zipkin:9411
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/