server:
  port: 8761

spring:
  output:
    ansi:
      enabled: always

  application:
    name: eureka-server

  zipkin:
    base-url: http://zipkin:9411
    
eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false