server:
  port: 8761

spring:
  output:
    ansi:
      enabled: always

  application:
    name: eureka-server

  zipkin:
    base-url: http://localhost:9411
    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false